# Generated by Django 2.2.5 on 2019-09-28 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='Rua')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('neighborhood', models.CharField(max_length=255, verbose_name='Bairro')),
                ('state', models.CharField(max_length=255, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('email', models.CharField(max_length=255, verbose_name='E-mail')),
                ('birth_date', models.CharField(max_length=10, verbose_name='Data de Nascimento')),
                ('cpf', models.BigIntegerField(verbose_name='CPF')),
                ('password', models.CharField(max_length=100, verbose_name='Senha')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to='core.Address')),
                ('friends', models.ManyToManyField(related_name='_user_friends_+', to='core.User')),
            ],
        ),
    ]
