# Generated by Django 2.2.5 on 2019-09-28 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sobrenome',
            new_name='surname',
        ),
    ]
